{
 "title": "Frauds Overview",
 "tags": [
  "fraud",
  "transactions"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Transactions Amount Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateTimeColDataType": "inserted_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \r\n  multiIf(\r\n    amt < 10, '0-10',\r\n    amt < 50, '10-50', \r\n    amt < 100, '50-100',\r\n    amt < 250, '100-250',\r\n    amt < 500, '250-1k',\r\n    '1k+'\r\n  ) as log_range,\r\n  count() as transactions\r\nFROM $table\r\nWHERE $timeFilter\r\nGROUP BY log_range\r\nORDER BY min(amt)\r\n",
     "rawQuery": "/* grafana dashboard='Frauds Overview', user='1' */\nSELECT \r\n  multiIf(\r\n    amt < 10, '0-10',\r\n    amt < 50, '10-50', \r\n    amt < 100, '50-100',\r\n    amt < 250, '100-250',\r\n    amt < 500, '250-1k',\r\n    '1k+'\r\n  ) as log_range,\r\n  count() as transactions\r\nFROM default.fraud_predictions\r\nWHERE inserted_at >= toDateTime(1752572653) AND inserted_at <= toDateTime(1752583453)\r\nGROUP BY log_range\r\nORDER BY min(amt)",
     "round": "0s",
     "table": "fraud_predictions"
    }
   ]
  },
  {
   "title": "Transactions Over Time (30s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 4, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateTimeColDataType": "inserted_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count()\r\nFROM fraud_predictions \r\nWHERE $timeFilter \r\nGROUP BY t\r\nORDER BY t",
     "rawQuery": "/* grafana dashboard='Frauds Overview', user='1' */\nSELECT (intDiv(toUInt32(inserted_at), 30) * 30) * 1000 as t, count()\r\nFROM fraud_predictions \r\nWHERE inserted_at >= toDateTime(1752572564) AND inserted_at <= toDateTime(1752583364) \r\nGROUP BY t\r\nORDER BY t",
     "round": "0s",
     "table": "fraud_predictions"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateTimeColDataType": "inserted_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT now() as t, count() \r\nFROM $table \r\nWHERE $timeFilter\r\n",
     "rawQuery": "/* grafana dashboard='Fraud Overview', user='1' */\nSELECT now() as t, count() \r\nFROM default.fraud_predictions \r\nWHERE inserted_at >= toDateTime(1752506100) AND inserted_at <= toDateTime(1752508799)",
     "rawSql": "SELECT count() FROM fraud_predictions",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Frauds Amount Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateTimeColDataType": "inserted_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \r\n  multiIf(\r\n    amt < 100, '0-100',\r\n    amt < 250, '100-250', \r\n    amt < 500, '250-500',\r\n    amt < 750, '500-750',\r\n    amt < 1000, '750-1k',\r\n    '1k+'\r\n  ) as log_range,\r\n  count() as transactions\r\nFROM $table\r\nWHERE $timeFilter AND fraud_prediction=1\r\nGROUP BY log_range\r\nORDER BY min(amt)\r\n",
     "rawQuery": "/* grafana dashboard='Frauds Overview', user='1' */\nSELECT \r\n  multiIf(\r\n    amt < 100, '0-100',\r\n    amt < 250, '100-250', \r\n    amt < 500, '250-500',\r\n    amt < 750, '500-750',\r\n    amt < 1000, '750-1k',\r\n    '1k+'\r\n  ) as log_range,\r\n  count() as transactions\r\nFROM default.fraud_predictions\r\nWHERE inserted_at >= toDateTime(1752576582) AND inserted_at <= toDateTime(1752587382) AND fraud_prediction=1\r\nGROUP BY log_range\r\nORDER BY min(amt)",
     "round": "0s",
     "table": "fraud_predictions"
    }
   ]
  },
  {
   "title": "Frauds Over Time (30s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 4, "y": 8 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateTimeColDataType": "inserted_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count() \r\nFROM $table \r\nWHERE $timeFilter \r\nAND fraud_prediction=1 \r\nGROUP BY t \r\nORDER BY t",
     "rawQuery": "/* grafana dashboard='Frauds Overview', user='1' */\nSELECT (intDiv(toUInt32(inserted_at), 30) * 30) * 1000 as t, count() \r\nFROM default.fraud_predictions \r\nWHERE inserted_at >= toDateTime(1752572571) AND inserted_at <= toDateTime(1752583371) \r\nAND fraud_prediction=1 \r\nGROUP BY t \r\nORDER BY t",
     "rawSql": "SELECT toStartOfHour(trans_date_trans_time) as time, count() as frauds FROM fraud_predictions WHERE fraud_prediction = 1 GROUP BY time ORDER BY time",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Detected Frauds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateTimeColDataType": "inserted_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count() FROM fraud_predictions WHERE $timeFilter AND fraud_prediction=1",
     "rawQuery": "/* grafana dashboard='Fraud Overview', user='1' */\nSELECT count() FROM fraud_predictions WHERE inserted_at >= toDateTime(1752506100) AND inserted_at <= toDateTime(1752508799) AND fraud_prediction=1",
     "rawSql": "SELECT count() FROM fraud_predictions WHERE fraud_prediction = 1",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Frauds Geolocalizations",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "contextWindowSize": "20",
     "database": "default",
     "dateTimeColDataType": "inserted_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * from fraud_predictions where $timeFilter AND fraud_prediction=1 \r\n",
     "rawQuery": "/* grafana dashboard='Frauds Overview', user='1' */\nselect * from fraud_predictions where inserted_at >= toDateTime(1752576610) AND inserted_at <= toDateTime(1752587410) AND fraud_prediction=1",
     "round": "0s",
     "table": "fraud_predictions"
    }
   ]
  },
  {
   "title": "Detected Frauds Informations",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateTimeColDataType": "inserted_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT inserted_at, trans_date_trans_time AS timestamp, trans_num, first, last, state,amt AS amount, fraud_probability\r\nFROM fraud_predictions\r\nWHERE $timeFilter AND fraud_prediction=1\r\nORDER BY inserted_at",
     "rawQuery": "/* grafana dashboard='Frauds Overview', user='1' */\nSELECT inserted_at, trans_date_trans_time AS timestamp, trans_num, first, last, state,amt AS amount, fraud_probability\r\nFROM fraud_predictions\r\nWHERE inserted_at >= toDateTime(1752576081) AND inserted_at <= toDateTime(1752586881) AND fraud_prediction=1\r\nORDER BY inserted_at",
     "round": "0s",
     "table": "fraud_predictions"
    }
   ]
  }
 ]
}