{
 "title": "Fraud Overview",
 "tags": [
  "fraud",
  "transactions"
 ],
 "refresh": "30s",
 "panels": [
  {
   "title": "Totale Transazioni",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 3 },
   "targets": [
    {
     "rawSql": "SELECT count() FROM fraud_predictions"
    }
   ]
  },
  {
   "title": "Transazioni Fraudolente",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 3 },
   "targets": [
    {
     "rawSql": "SELECT count() FROM fraud_predictions WHERE fraud_prediction = 1"
    }
   ]
  },
  {
   "title": "Frodi nel tempo",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 3, "w": 12, "h": 6 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfHour(trans_date_trans_time) as time, count() as frauds FROM fraud_predictions WHERE fraud_prediction = 1 GROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "Categorie Frodi",
   "type": "piechart",
   "gridPos": { "x": 0, "y": 9, "w": 12, "h": 5 },
   "targets": [
    {
     "rawSql": "SELECT category, count() AS count FROM fraud_predictions WHERE fraud_prediction = 1 GROUP BY category ORDER BY count DESC"
    }
   ]
  }
 ]
}