services:

  producer:
    build:
      context: ./producer     
      dockerfile: Dockerfile
    container_name: producer                 
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      KAFKA_TOPIC: fraud-transactions
      TEST_DATA_PATH: fraudTest.csv
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  kafka1:
    image: bitnami/kafka:3.7.0
    container_name: kafka1
    ports:
      - 9092:9092
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:19092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka1:19092,2@kafka2:19093,3@kafka3:19094
      KAFKA_KRAFT_CLUSTER_ID: Nru2U1JQQT-RKA0UapBN3w
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      - kafka1_data:/bitnami/kafka

  kafka2:
    image: bitnami/kafka:3.7.0
    container_name: kafka2
    ports:
      - "9093:9092"
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:19093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka1:19092,2@kafka2:19093,3@kafka3:19094
      KAFKA_KRAFT_CLUSTER_ID: Nru2U1JQQT-RKA0UapBN3w
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      - kafka2_data:/bitnami/kafka

  kafka3:
    image: bitnami/kafka:3.7.0
    container_name: kafka3
    ports:
      - "9094:9092"
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:19094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka1:19092,2@kafka2:19093,3@kafka3:19094
      KAFKA_KRAFT_CLUSTER_ID: Nru2U1JQQT-RKA0UapBN3w
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      - kafka3_data:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - 8080:8080
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092,kafka3:9092

  kafka-init:
    image: bitnami/kafka:3.7.0
    container_name: kafka-init
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    volumes:
      - ./kafka/code/init-topic.sh:/init-topic.sh
    environment:
      KAFKA_TOPIC: fraud-transactions
      KAFKA_BOOTSTRAP_SERVER: kafka1:9092
    command: ["/bin/bash", "/init-topic.sh"]

  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    ports:
      - 4040:4040
      - 7077:7077
      - 8081:8080
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      HOME: /tmp/spark-home
    volumes:
      - ./spark/code:/opt/bitnami/spark/apps
      - spark_data:/opt/bitnami/spark/data
      - ./model/xgb_full_pipeline.pkl:/opt/bitnami/spark/apps/xgb_full_pipeline.pkl
      - ./spark/jars:/opt/spark/jars

  spark-worker-1:
    image: bitnami/spark:3.5
    container_name: spark-worker-1
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 3G
      SPARK_WORKER_CORES: 1
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
    depends_on:
      - spark-master
      - clickhouse
    volumes:
      - ./spark/code:/opt/bitnami/spark/apps
      - ./model/xgb_full_pipeline.pkl:/opt/bitnami/spark/apps/xgb_full_pipeline.pkl
      - ./spark/jars:/opt/spark/jars
    command: ["/bin/bash", "/opt/bitnami/spark/apps/run_workers.sh"]
   

  spark-worker-2:
    image: bitnami/spark:3.5
    container_name: spark-worker-2
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 3G
      SPARK_WORKER_CORES: 1
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
    depends_on:
      - spark-master
      - clickhouse
    volumes:
      - ./spark/code:/opt/bitnami/spark/apps
      - ./model/xgb_full_pipeline.pkl:/opt/bitnami/spark/apps/xgb_full_pipeline.pkl
      - ./spark/jars:/opt/spark/jars
    command: ["/bin/bash", "/opt/bitnami/spark/apps/run_workers.sh"]

  spark-worker-3:
    image: bitnami/spark:3.5
    container_name: spark-worker-3
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 3G
      SPARK_WORKER_CORES: 1
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
    depends_on:
      - spark-master
      - clickhouse
    volumes:
      - ./spark/code:/opt/bitnami/spark/apps
      - ./model/xgb_full_pipeline.pkl:/opt/bitnami/spark/apps/xgb_full_pipeline.pkl
      - ./spark/jars:/opt/spark/jars
    command: ["/bin/bash", "/opt/bitnami/spark/apps/run_workers.sh"]

  spark-submit:
    image: bitnami/spark:3.5
    container_name: spark-submit
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
      - spark-worker-3
      - clickhouse
    environment:
      PYTHONPATH: /opt/bitnami/python/lib/python3.9/site-packages
    volumes:
      - ./spark/code:/opt/bitnami/spark/apps
      - spark_data:/opt/bitnami/spark/data
      - ./model/xgb_full_pipeline.pkl:/opt/bitnami/spark/apps/xgb_full_pipeline.pkl
      - ./spark/jars:/opt/spark/jars
    command: ["/opt/bitnami/spark/apps/submit.sh"]
    restart: no

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DB: default
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/config/users.xml:/etc/clickhouse-server/users.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - clickhouse

volumes:
  kafka1_data:
  kafka2_data:
  kafka3_data:
  spark_data:
  clickhouse_data:
  grafana_data:

