apiVersion: 1

datasources:
  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    basicAuth: false
    jsonData:
      username: grafana
    secureJsonData:
      password: grafana123
    isDefault: true
    editable: true